# Generated by Django 4.1.3 on 2022-12-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M')], max_length=6),
        ),
    ]
