# Generated by Django 4.1.3 on 2022-12-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_alter_visitor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=models.IntegerField(choices=[(0, 'under 5'), (5, '6 - 10'), (10, '11 - 15'), (15, '16 - 20'), (20, '20 - 30'), (30, '30 - 40'), (40, '40 - 50'), (50, '50 - 60'), (60, 'above 60')]),
        ),
    ]
