# Generated by Django 4.1.3 on 2022-12-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_alter_visitor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=models.IntegerField(choices=[(0, 'under 5'), (5, '5 - 9'), (10, '10 - 14'), (15, '15 - 19'), (20, '20 - 30'), (30, '30 - 40'), (40, '40 - 50'), (50, '50 - 60'), (60, 'above 60')]),
        ),
    ]
