# Generated by Django 4.1.3 on 2022-12-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_alter_visitor_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='thumb',
        ),
    ]
